server.port=8083
vaadin.launch-browser=true
spring.application.name=EcomElectronicsCustomerManagement
spring.datasource.url=jdbc:postgresql://localhost:5432/CustomerManagement_DB
spring.datasource.username=postgres
spring.datasource.password=7_In76*529
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#logging.level.root=INFO
#logging.level.org.springframework.web=DEBUG
#logging.level.ecommerce.electronics=DEBUG
product.service.url=http://localhost:8080
order.service.url=http://localhost:8082


